name: Deploy to Firebase Hosting on push

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md' 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'  
    - name: Install Dependencies
      run: npm install
    - name: Build React App
      run: npm run build
   - name: Deploy to Firebase Hosting
     uses: FirebaseExtended/action-hosting-deploy@v0
     with:
      repoToken: ${{ secrets.GITHUB_TOKEN }}
      firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_TALLER3FRONTEND2025 }}
      projectId: taller3frontend2025
